build:
  maxIssues: 0
  excludeCorrectable: false

complexity:
  active: true
  ComplexCondition:
    active: true
    threshold: 4
  CyclomaticComplexMethod:
    active: true
    threshold: 15
  LongMethod:
    active: true
    threshold: 150
  LongParameterList:
    active: true
    functionThreshold: 15
    constructorThreshold: 15
  LargeClass:
    active: true
    threshold: 600
  TooManyFunctions:
    active: true
    thresholdInFiles: 20
    thresholdInClasses: 20

style:
  active: true
  MagicNumber:
    active: true
    ignoreNumbers:
      - '-1'
      - '0'
      - '1'
      - '2'
      - '1024'
    ignoreHashCodeFunction: true
    ignorePropertyDeclaration: true
    ignoreLocalVariableDeclaration: true
    ignoreConstantDeclaration: true
    ignoreAnnotation: true
    ignoreNamedArgument: true
    ignoreEnums: true
  WildcardImport:
    active: true
    excludeImports:
      - 'kotlinx.android.synthetic.*'
      - 'androidx.compose.ui.graphics.*'
      - 'androidx.compose.material.icons.*'
      - 'androidx.compose.animation.*'
      - 'androidx.compose.foundation.layout.*'
      - 'androidx.compose.material3.*'
      - 'androidx.compose.runtime.*'
  MaxLineLength:
    active: true
    maxLineLength: 140
  UnusedImports:
    active: true

naming:
  active: true
  FunctionNaming:
    active: true
    functionPattern: '[a-zA-Z][a-zA-Z0-9]*' # Allow uppercase for Composables
  ClassNaming:
    active: true
    classPattern: '[A-Z][a-zA-Z0-9]*'

exceptions:
  active: true
  TooGenericExceptionCaught:
    active: true
    exceptionNames:
      - 'Error'
      - 'Throwable'
      - 'RuntimeException'
      - 'NullPointerException'
