name: Build Android

on:
  workflow_call:
    secrets:
      ANDROID_KEYSTORE_B64:
        required: true
      KEYSTORE_PASSWORD:
        required: true
      KEY_ALIAS:
        required: true
      KEY_PASSWORD:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup Java JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Make gradlew executable
        run: chmod +x ./android/gradlew

      - name: Decode Keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_B64 }}" | base64 --decode > android/my-release-key.jks

      - name: Set up Versioning
        run: |
          # Remove 'v' prefix if present for version name
          VERSION_NAME="${GITHUB_REF_NAME#v}"
          echo "VERSION_NAME=${VERSION_NAME}" >> $GITHUB_ENV
          echo "VERSION_CODE=${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      - name: Build Release APK
        working-directory: ./android
        run: ./gradlew assembleRelease
        env:
          KEYSTORE_PATH: ${{ github.workspace }}/android/my-release-key.jks
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Generate Checksum
        working-directory: ./android/app/build/outputs/apk/release
        run: sha256sum app-release.apk > checksum-android.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: android-build
          retention-days: 5
          path: |
            android/app/build/outputs/apk/release/app-release.apk
            android/app/build/outputs/apk/release/checksum-android.txt
